# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [4]:
pip install -r requirements.txt


[notice] A new release of pip is available: 24.3.1 -> 25.2
[notice] To update, run: /opt/homebrew/Cellar/jupyterlab/4.3.4_1/libexec/bin/python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [5]:
%run generators.py

In [6]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [14]:
np.__version__

'2.3.1'

#### 3. Create a null vector of size 10 (★☆☆)

In [40]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [44]:
arr.nbytes

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [39]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [37]:
arr = np.zeros(10)
arr[4] = 1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [45]:
arr = np.arange(10, 50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [53]:
reverse_arr = arr[::-1]
print(reverse_arr)

newarr = np.flip(arr)
print(newarr)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [29]:
arr = np.arange(0,9).reshape(3, 3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [9]:
arr = np.array([1,2,0,0,4,0])
x = np.where(arr!=0)
print(x)

nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)
(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [58]:
arr = np.eye(3, 3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [24]:
from numpy import random

In [20]:
arr = random.random(size=(3, 3, 3))
print(arr)

[[[0.97256707 0.77832368 0.79626483]
  [0.33819429 0.37495445 0.0874237 ]
  [0.98973157 0.65426949 0.70475639]]

 [[0.20884894 0.7170674  0.86197271]
  [0.65120427 0.33416698 0.76370183]
  [0.39735305 0.98853601 0.38452718]]

 [[0.70226624 0.00251811 0.07390796]
  [0.66834732 0.21426691 0.95359621]
  [0.96096072 0.60539961 0.89375892]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [24]:
arr = random.random(size=(10,10)) 
max_v = arr.max()
min_v = arr.min()
print(arr, max_v, min_v)

[[0.52891847 0.55666243 0.72252506 0.98787423 0.7280544  0.52774772
  0.16699615 0.2497727  0.81241171 0.56523542]
 [0.39100427 0.54695988 0.00303818 0.80599849 0.72191777 0.39359272
  0.74936999 0.2330601  0.06407435 0.32284869]
 [0.53900037 0.27080033 0.98613854 0.44177307 0.86716003 0.04994149
  0.30773452 0.53287479 0.98774914 0.53325703]
 [0.18480949 0.80404723 0.50785428 0.19013919 0.91411296 0.48118518
  0.3866686  0.37488617 0.34906574 0.88449071]
 [0.92874433 0.63818638 0.61675432 0.53542339 0.58845855 0.71625831
  0.98084528 0.66442648 0.89510499 0.96731518]
 [0.76123321 0.27903943 0.93821843 0.68184518 0.67634199 0.52411528
  0.17378737 0.35387164 0.15142493 0.68645259]
 [0.75725133 0.93536247 0.15760902 0.39069405 0.21289115 0.01845684
  0.85470473 0.18525878 0.60306461 0.96994089]
 [0.32441773 0.55898906 0.17606854 0.13407096 0.19009191 0.05062909
  0.58048814 0.69062637 0.0018897  0.10271966]
 [0.92486992 0.76551897 0.87882984 0.75814678 0.17495797 0.60387027
  0.47003634

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [28]:
arr = random.random(size=(30))
mean_v = arr.mean()
print(mean_v)

0.4662733720875109


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [12]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [8]:
arr = np.diag([1, 2, 3, 4, 5])
print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

#### 22. Normalize a 5x5 random matrix (★☆☆)

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [15]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[0.]


/var/folders/ls/lmkg84h154l871cbkwhq2nnc0000gn/T/ipykernel_22515/3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/var/folders/ls/lmkg84h154l871cbkwhq2nnc0000gn/T/ipykernel_22515/3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/var/folders/ls/lmkg84h154l871cbkwhq2nnc0000gn/T/ipykernel_22515/3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

In [22]:
arr1 = np.arange(0,13)
arr2 = np.arange(0,4)
res = np.intersect1d(arr1, arr2, assume_unique=True)
print(res)

[0 1 2 3]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [30]:
arr = random.random(size=(10))
newarr = np.sort(arr)
print(newarr)

[0.08965708 0.18409894 0.27033637 0.52753899 0.56998735 0.58190494
 0.65185113 0.78060314 0.8063345  0.87732827]


#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

#### * Create a rank 2 (2D) array that resembles the matrix below.
[[11 12 13 14]
 [15 16 17 18]]
 (https://libguides.ntu.edu.sg/python/introductiontonumpy)

In [2]:
arr = np.array([[11, 12, 13, 14], [15, 16, 17, 18]])
print(arr)

[[11 12 13 14]
 [15 16 17 18]]


#### * Find out the shape of the above array.

In [3]:
print(arr.shape)

(2, 4)


#### * Create an array with 4 rows and 3 columns of zeros.

In [4]:
arr = np.zeros((4, 3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### * Create an array of ones that has 3 rows and 4 columns. 

In [5]:
arr = np.ones((3, 4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


#### * Create an array containing integers 4 to 13 inclusive. 

In [6]:
arr = np.arange(4, 14)
print(arr)

[ 4  5  6  7  8  9 10 11 12 13]


#### * Create an array containing [0., 1.5, 3., 4.5].

In [9]:
arr = np.linspace(0, 4.5, 4)
print(arr)

[0.  1.5 3.  4.5]


#### * Create a 2 by 2 array containing '4' in each position. 

In [10]:
arr = np.full((2, 2), 4)
print(arr)

[[4 4]
 [4 4]]


#### * Create 2 matrices:

i. Identity matrix of size 4

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

ii. Diagonal matrix with [10,12] as the diagonals 

[[10  0]
 [ 0 12]]

In [16]:
arr1 = np.eye(4)
arr2 = np.diag([10, 12])
print(arr1)
print(arr2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[10  0]
 [ 0 12]]


#### * Create a 3 by 3 array with random floats in [0, 10].

In [2]:
arr = np.random.random((3,3))*10
print(arr)

[[8.80787153 3.45227784 5.98878508]
 [6.94579809 5.52160043 7.42244788]
 [5.34336395 3.7376593  6.70314183]]


#### *  Create a 3 by 3 array with random integers in [10, 20].

In [13]:
arr = np.random.randint(10, 20, size=(3, 3))
print(arr)

[[16 11 19]
 [11 11 13]
 [14 19 15]]


#### *  Use this array for the following practice:

myArray = np.array([[11,12,13], [14,15,16], [17,18,19]])

a. Get a subarray of the first row and first 2 columns. Your results should look like this:

[11 12]
 

b. Change all elements in 1st and second row to 0. Your results should look like this:

[[ 0  0  0]
 [ 0  0  0]
 [17 18 19]]

In [11]:
myArray = np.array([[11,12,13], [14,15,16], [17,18,19]])
print(myArray[:1, :2])

[[11 12]]


In [14]:
myArray[0:2] = 0
print(myArray)

[[ 0  0  0]
 [ 0  0  0]
 [17 18 19]]


#### *  Create an array that contains [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20] and reverse the order.

In [17]:
arr = np.arange(21)
print(arr[::-1])

[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


#### *  Reshape the array to an array with 3 rows. Your results should look like this:

[[11 12]
 [13 14]
 [15 16]]
 
Use this array for the following practice: 

myArray = np.array([[11,12,13], [14,15,16]])

In [18]:
myArray = np.array([[11,12,13], [14,15,16]])
arr_reshaped = myArray.reshape(3, -1)
print(arr_reshaped)

[[11 12]
 [13 14]
 [15 16]]


#### *  Use this array for the following practice: 

myArray = np.arange(10)

1. Find the square of every number in array

2. Find the square root of every number in array

3. Multiply the square of each number in array with its respective square root

In [22]:
myArray = np.arange(10)
print(myArray)
print(np.square(myArray))
print(np.sqrt(myArray))
print(np.multiply(np.square(myArray), np.sqrt(myArray)))

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  4  9 16 25 36 49 64 81]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[  0.           1.           5.65685425  15.58845727  32.
  55.90169944  88.18163074 129.64181424 181.01933598 243.        ]


#### *  Rearrange the following arrays and stack them vertically with 5 columns:

myArray_1 = np.arange(20)

myArray_2 = np.arange(30)

In [29]:
myArray_1 = np.arange(20).reshape(4, 5)
#myArray_1 = np.arange(20).reshape(-1, 5)
myArray_2 = np.arange(30).reshape(6, 5)
#myArray_2 = np.arange(30).reshape(-1, 5)
print(np.concatenate((myArray_1, myArray_2), axis=0))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


#### *  Use this array for the following practice: 

myArray = np.array([[11,12,13], [14,15,16], [17,18,19]])

1. Add a new row of elements containing 20, 21 and 22

2. Add a new column of elements containing 30, 40 and 50

In [31]:
myArray = np.array([[11,12,13], [14,15,16], [17,18,19]])
new_arr_r = np.append(myArray, [[20, 21, 22]], axis=0)
new_arr_c = np.append(myArray, [[30], [40], [50]], axis=1)
print(new_arr_r)
print(new_arr_c)

[[11 12 13]
 [14 15 16]
 [17 18 19]
 [20 21 22]]
[[11 12 13 30]
 [14 15 16 40]
 [17 18 19 50]]


#### *  Add 1 column of 1 to this array: myArray = np.zeros((2,2)).

In [34]:
myArray = np.zeros((2,2))
new_arr = np.append(myArray,np.ones((2,1)),axis = 1)
print(new_arr)

[[0. 0. 1.]
 [0. 0. 1.]]


#### *  Add 2 rows of 2 to the answer from part 1.

In [35]:
new_arr_1 = np.append(new_arr,[[2,2,2],[2,2,2]],axis = 0)
print(new_arr_1)

[[0. 0. 1.]
 [0. 0. 1.]
 [2. 2. 2.]
 [2. 2. 2.]]


#### *  Remove the elements from the middle column of this array:

myArray = np.matrix([[1, 2, 3], [4, 5, 6], [9, 8, 7]])

In [3]:
myArray = np.matrix([[1, 2, 3], [4, 5, 6], [9, 8, 7]])
newarr = np.delete(myArray, 1, axis=1)
print(newarr)

[[1 3]
 [4 6]
 [9 7]]


#### *   Find the unique elements in this array:

myArray_1 = np.array([[2,2,3,4],[3,2,3,4]])

In [5]:
myArray_1 = np.array([[2,2,3,4],[3,2,3,4]])
unique_elems = np.unique(myArray_1)
print(unique_elems)

[2 3 4]


#### * Sort the elements in this array by its rows:

myArray_2 = np.array([[2,3,1,4],[7,5,6,8]])

In [6]:
myArray_2 = np.array([[2,3,1,4],[7,5,6,8]])
sorted_arr = np.sort(myArray_2, axis=1)
print(sorted_arr)

[[1 2 3 4]
 [5 6 7 8]]


#### * Use this array for the following practice: 

myArray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

1. Find the mean of this array

2. Find the standard deviation by rows

3. Find the maximum value in the array

In [7]:
myArray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.mean(myArray))
print(np.std(myArray, axis=1))
print(np.max(myArray))

5.0
[0.81649658 0.81649658 0.81649658]
9


#### * Use these arrays for the following practice: 

myArray_1 = np.array([2,2,3,4])

myArray_2 = np.array([3,2,3,4])
 

1. Find the elements that are the same in both arrays

2. Find elements in myArray_1 that are smaller than or equal to its corresponding element in myArray_2

3. Find the elements in myArray_1 that is bigger than 2

In [12]:
myArray_1 = np.array([2,2,3,4])
myArray_2 = np.array([3,2,3,4])
print(myArray_1[np.where(myArray_1 == myArray_2)])
print(myArray_1[np.where(myArray_1 <= myArray_2)])
print(myArray_1[np.where(myArray_1 > 2)])

[2 3 4]
[2 2 3 4]
[3 4]


#### * Replace all odd numbers in the given array with -1

Start with:

exercise_1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
exercise_1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
exercise_1[exercise_1 % 2 != 0] = -1
print(exercise_1)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


#### * Convert a 1-D array into a 2-D array with 3 rows

Start with:

exercise_2 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
exercise_2 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
new = exercise_2.reshape(3, -1)
print(new)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### * Add 202 to all the values in given array

Start with:

exercise_3 = np.arange(4).reshape(2,-1)

In [18]:
exercise_3 = np.arange(4).reshape(2,-1)
res = np.add(exercise_3, 202)
print(res)

[[202 203]
 [204 205]]


#### * Generate a 1-D array of 10 random integers. Each integer should be a number between 30 and 40 (inclusive).

In [63]:
res = np.random.randint(30, 41, size = (10))
print(res)

[37 33 40 38 31 31 31 34 39 37]


#### * Find the positions of:

elements in x where its value is more than its corresponding element in y, and
elements in x where its value is equals to its corresponding element in y.

Start with these:

x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89]) 

y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])


In [64]:
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89])
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])
print(np.where(x > y))
print(np.where(x == y))

(array([1, 2, 4, 5, 6, 7, 8, 9]),)
(array([0]),)


#### * Extract the first four columns of this 2-D array

Start with this: 

exercise_6 = np.arange(100).reshape(5,-1)

In [67]:
exercise_6 = np.arange(100).reshape(5,-1)
print(exercise_6[:, :4])

[[ 0  1  2  3]
 [20 21 22 23]
 [40 41 42 43]
 [60 61 62 63]
 [80 81 82 83]]
